name: Test

on:
  push:
    branches: 
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            shell: bash
          - os: macos-latest
            shell: bash

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      with:
        go-version-file: go.mod

    - name: Test
      run: |
        go test -v ./...
